JYNS_USERNAME: ""
JYNS_PASSWORD: ""
JYNS_HOME: ""

JYNS_SSH_IP: ""

JYNS_SLURM_USERNAME: ""
JYNS_SLURM_HOST: ""
JYNS_SLURM_DIR: ""
JYNS_SLURM_PEM: ""

USER: ""
JYNS_AWS_INSTANCE_PROFILE: ""
JYNS_AWS_S3_BUCKET: ""

JYNS_GCP_PROJECT: ""
JYNS_GS_BUCKET: ""
